Feat: main page
eman-maheen/auxcube pull request #1
Opened 2024-03-28 17:18 UTC by eman-maheen

2024-03-31 22:55 UTC, ReallyVirtual requested changes
We'll bring this to the auxcube repos once my comments are resolved.

2024-03-31 22:55 UTC, ReallyVirtual commented on src/app.html
>  		<link rel="icon" href="%sveltekit.assets%/favicon.svg" />
@eman-maheen don't these <link tags help with speed? Why are we taking them out?

2024-03-31 22:55 UTC, ReallyVirtual commented on src/lib/components/Footer.svelte
>    import { titleToSlug } from '$lib/content/site';
It would be better to import const menu items from a file rather than embed them in the file, so they can be changed from a single place later.

2024-03-31 22:55 UTC, ReallyVirtual commented on src/lib/content/site.ts
The footer links can come here too

2024-03-31 22:55 UTC, ReallyVirtual commented on src/lib/content/site.ts
> +        { title: "Home",  skipScaffold: true, },
The subtitle/snippet were there to be used in the SEO header tags. How are we handling that data as it is associated to each page.

2024-04-01 09:38 UTC, eman-maheen commented on src/app.html
>  		<link rel="icon" href="%sveltekit.assets%/favicon.svg" />
I took out the link tags with pre-loaded fonts only. These fonts are no longer being used and unused fonts were making the lighthouse score low @ReallyVirtual

2024-04-02 00:27 UTC, ReallyVirtual commented on src/lib/content/site.ts
> +        { title: "Home",  skipScaffold: true, },
@eman-maheen this comment...

2024-04-02 03:28 UTC, ReallyVirtual approved these changes

2024-04-02 03:28 UTC, merged